// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"fmt"
	"time"

	"github.com/mattrax/Mattrax/pkg/null"
)

type DeviceState string

const (
	DeviceStateDeploying      DeviceState = "deploying"
	DeviceStateManaged        DeviceState = "managed"
	DeviceStateUserUnenrolled DeviceState = "user_unenrolled"
	DeviceStateMissing        DeviceState = "missing"
)

func (e *DeviceState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceState(s)
	case string:
		*e = DeviceState(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceState: %T", src)
	}
	return nil
}

type EnrollmentType string

const (
	EnrollmentTypeUnenrolled EnrollmentType = "Unenrolled"
	EnrollmentTypeUser       EnrollmentType = "User"
	EnrollmentTypeDevice     EnrollmentType = "Device"
)

func (e *EnrollmentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnrollmentType(s)
	case string:
		*e = EnrollmentType(s)
	default:
		return fmt.Errorf("unsupported scan type for EnrollmentType: %T", src)
	}
	return nil
}

type UserPermissionLevel string

const (
	UserPermissionLevelUser          UserPermissionLevel = "user"
	UserPermissionLevelAdministrator UserPermissionLevel = "administrator"
)

func (e *UserPermissionLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserPermissionLevel(s)
	case string:
		*e = UserPermissionLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for UserPermissionLevel: %T", src)
	}
	return nil
}

type Certificate struct {
	ID   string `json:"id"`
	Cert []byte `json:"cert"`
	Key  []byte `json:"key"`
}

type Device struct {
	ID               int32          `json:"id"`
	Udid             string         `json:"udid"`
	State            DeviceState    `json:"state"`
	EnrollmentType   EnrollmentType `json:"enrollment_type"`
	Name             string         `json:"name"`
	Description      null.String    `json:"description"`
	Model            string         `json:"model"`
	HwDevID          string         `json:"hw_dev_id"`
	OperatingSystem  string         `json:"operating_system"`
	AzureDid         null.String    `json:"azure_did"`
	NodecacheVersion string         `json:"nodecache_version"`
	Lastseen         time.Time      `json:"lastseen"`
	LastseenStatus   int32          `json:"lastseen_status"`
	EnrolledAt       time.Time      `json:"enrolled_at"`
	EnrolledBy       null.String    `json:"enrolled_by"`
}

type DeviceCache struct {
	DeviceID    int32         `json:"device_id"`
	PayloadID   sql.NullInt32 `json:"payload_id"`
	InventoryID sql.NullInt32 `json:"inventory_id"`
	CacheID     int32         `json:"cache_id"`
}

type DeviceInventory struct {
	ID       int32  `json:"id"`
	DeviceID int32  `json:"device_id"`
	Uri      string `json:"uri"`
	Format   string `json:"format"`
	Value    string `json:"value"`
}

type DeviceSessionCache struct {
}

type Group struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Priority    int16  `json:"priority"`
}

type GroupDevice struct {
	GroupID  int32 `json:"group_id"`
	DeviceID int32 `json:"device_id"`
}

type GroupPolicy struct {
	GroupID  sql.NullInt32 `json:"group_id"`
	PolicyID sql.NullInt32 `json:"policy_id"`
}

type PoliciesPayload struct {
	ID       int32         `json:"id"`
	PolicyID sql.NullInt32 `json:"policy_id"`
	Uri      string        `json:"uri"`
	Format   string        `json:"format"`
	Type     string        `json:"type"`
	Value    string        `json:"value"`
	Exec     bool          `json:"exec"`
}

type Policy struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Priority    int16  `json:"priority"`
}

type Setting struct {
	TenantName        string `json:"tenant_name"`
	TenantEmail       string `json:"tenant_email"`
	TenantWebsite     string `json:"tenant_website"`
	TenantPhone       string `json:"tenant_phone"`
	TenantAzureid     string `json:"tenant_azureid"`
	DisableEnrollment bool   `json:"disable_enrollment"`
}

type User struct {
	Upn             string              `json:"upn"`
	Fullname        string              `json:"fullname"`
	Password        null.String         `json:"password"`
	MfaToken        null.String         `json:"mfa_token"`
	AzureadOid      null.String         `json:"azuread_oid"`
	PermissionLevel UserPermissionLevel `json:"permission_level"`
}
