// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createRawCert = `-- name: CreateRawCert :exec
INSERT INTO certificates(id, cert, key) VALUES ($1, $2, $3)
`

type CreateRawCertParams struct {
	ID   string `json:"id"`
	Cert []byte `json:"cert"`
	Key  []byte `json:"key"`
}

func (q *Queries) CreateRawCert(ctx context.Context, arg CreateRawCertParams) error {
	_, err := q.exec(ctx, q.createRawCertStmt, createRawCert, arg.ID, arg.Cert, arg.Key)
	return err
}

const deleteDeviceCacheNode = `-- name: DeleteDeviceCacheNode :exec

DELETE FROM device_cache WHERE device_id = $1 AND payload_id = $2
`

type DeleteDeviceCacheNodeParams struct {
	DeviceID  int32 `json:"device_id"`
	PayloadID int32 `json:"payload_id"`
}

// TODO: cache_id
func (q *Queries) DeleteDeviceCacheNode(ctx context.Context, arg DeleteDeviceCacheNodeParams) error {
	_, err := q.exec(ctx, q.deleteDeviceCacheNodeStmt, deleteDeviceCacheNode, arg.DeviceID, arg.PayloadID)
	return err
}

const deviceCheckinStatus = `-- name: DeviceCheckinStatus :exec
UPDATE devices SET lastseen=NOW(), lastseen_status=$2 WHERE id = $1
`

type DeviceCheckinStatusParams struct {
	ID             int32 `json:"id"`
	LastseenStatus int32 `json:"lastseen_status"`
}

func (q *Queries) DeviceCheckinStatus(ctx context.Context, arg DeviceCheckinStatusParams) error {
	_, err := q.exec(ctx, q.deviceCheckinStatusStmt, deviceCheckinStatus, arg.ID, arg.LastseenStatus)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, udid, state, enrollment_type, name, model, serial_number, operating_system, azure_did, nodecache_version, lastseen, lastseen_status, enrolled_at, enrolled_by FROM devices WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id int32) (Device, error) {
	row := q.queryRow(ctx, q.getDeviceStmt, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Udid,
		&i.State,
		&i.EnrollmentType,
		&i.Name,
		&i.Model,
		&i.SerialNumber,
		&i.OperatingSystem,
		&i.AzureDid,
		&i.NodecacheVersion,
		&i.Lastseen,
		&i.LastseenStatus,
		&i.EnrolledAt,
		&i.EnrolledBy,
	)
	return i, err
}

const getDeviceByUDID = `-- name: GetDeviceByUDID :one
SELECT id, udid, state, enrollment_type, name, model, serial_number, operating_system, azure_did, nodecache_version, lastseen, lastseen_status, enrolled_at, enrolled_by FROM devices WHERE udid = $1 LIMIT 1
`

func (q *Queries) GetDeviceByUDID(ctx context.Context, udid string) (Device, error) {
	row := q.queryRow(ctx, q.getDeviceByUDIDStmt, getDeviceByUDID, udid)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Udid,
		&i.State,
		&i.EnrollmentType,
		&i.Name,
		&i.Model,
		&i.SerialNumber,
		&i.OperatingSystem,
		&i.AzureDid,
		&i.NodecacheVersion,
		&i.Lastseen,
		&i.LastseenStatus,
		&i.EnrolledAt,
		&i.EnrolledBy,
	)
	return i, err
}

const getDevicesDetachedPayloads = `-- name: GetDevicesDetachedPayloads :many
SELECT id, uri, exec FROM device_cache INNER JOIN policies_payload ON policies_payload.id=device_cache.payload_id WHERE device_cache.device_id = $1 AND NOT EXISTS (SELECT policies_payload.id, policies_payload.policy_id, policies_payload.uri, policies_payload.format, policies_payload.type, policies_payload.value, policies_payload.exec FROM group_devices INNER JOIN group_policies ON group_policies.group_id=group_devices.group_id INNER JOIN policies_payload ON policies_payload.policy_id=group_policies.policy_id WHERE group_devices.device_id = device_cache.device_id)
`

type GetDevicesDetachedPayloadsRow struct {
	ID   int32  `json:"id"`
	Uri  string `json:"uri"`
	Exec bool   `json:"exec"`
}

func (q *Queries) GetDevicesDetachedPayloads(ctx context.Context, deviceID int32) ([]GetDevicesDetachedPayloadsRow, error) {
	rows, err := q.query(ctx, q.getDevicesDetachedPayloadsStmt, getDevicesDetachedPayloads, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDevicesDetachedPayloadsRow
	for rows.Next() {
		var i GetDevicesDetachedPayloadsRow
		if err := rows.Scan(&i.ID, &i.Uri, &i.Exec); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevicesPayloads = `-- name: GetDevicesPayloads :many

SELECT policies_payload.id, policies_payload.policy_id, policies_payload.uri, policies_payload.format, policies_payload.type, policies_payload.value, policies_payload.exec FROM group_devices INNER JOIN group_policies ON group_policies.group_id=group_devices.group_id INNER JOIN policies_payload ON policies_payload.policy_id=group_policies.policy_id WHERE group_devices.device_id = $1
`

// TODO: Merge this with last checkin status
func (q *Queries) GetDevicesPayloads(ctx context.Context, deviceID int32) ([]PoliciesPayload, error) {
	rows, err := q.query(ctx, q.getDevicesPayloadsStmt, getDevicesPayloads, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoliciesPayload
	for rows.Next() {
		var i PoliciesPayload
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Uri,
			&i.Format,
			&i.Type,
			&i.Value,
			&i.Exec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevicesPayloadsAwaitingDeployment = `-- name: GetDevicesPayloadsAwaitingDeployment :many
SELECT id, uri, format, type, value, exec FROM group_devices INNER JOIN group_policies ON group_policies.group_id=group_devices.group_id INNER JOIN policies_payload ON policies_payload.policy_id=group_policies.policy_id WHERE group_devices.device_id = $1 AND NOT EXISTS (SELECT 1 FROM device_cache WHERE device_cache.payload_id = policies_payload.id AND device_cache.device_id=group_devices.device_id)
`

type GetDevicesPayloadsAwaitingDeploymentRow struct {
	ID     int32  `json:"id"`
	Uri    string `json:"uri"`
	Format string `json:"format"`
	Type   string `json:"type"`
	Value  string `json:"value"`
	Exec   bool   `json:"exec"`
}

func (q *Queries) GetDevicesPayloadsAwaitingDeployment(ctx context.Context, deviceID int32) ([]GetDevicesPayloadsAwaitingDeploymentRow, error) {
	rows, err := q.query(ctx, q.getDevicesPayloadsAwaitingDeploymentStmt, getDevicesPayloadsAwaitingDeployment, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDevicesPayloadsAwaitingDeploymentRow
	for rows.Next() {
		var i GetDevicesPayloadsAwaitingDeploymentRow
		if err := rows.Scan(
			&i.ID,
			&i.Uri,
			&i.Format,
			&i.Type,
			&i.Value,
			&i.Exec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPoliciesPayloads = `-- name: GetPoliciesPayloads :many
SELECT id, policy_id, uri, format, type, value, exec FROM policies_payload WHERE policy_id = $1
`

func (q *Queries) GetPoliciesPayloads(ctx context.Context, policyID sql.NullInt32) ([]PoliciesPayload, error) {
	rows, err := q.query(ctx, q.getPoliciesPayloadsStmt, getPoliciesPayloads, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoliciesPayload
	for rows.Next() {
		var i PoliciesPayload
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Uri,
			&i.Format,
			&i.Type,
			&i.Value,
			&i.Exec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, name, description, priority FROM policies WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPolicy(ctx context.Context, id int32) (Policy, error) {
	row := q.queryRow(ctx, q.getPolicyStmt, getPolicy, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Priority,
	)
	return i, err
}

const getRawCert = `-- name: GetRawCert :one
SELECT cert, key FROM certificates WHERE id = $1 LIMIT 1
`

type GetRawCertRow struct {
	Cert []byte `json:"cert"`
	Key  []byte `json:"key"`
}

func (q *Queries) GetRawCert(ctx context.Context, id string) (GetRawCertRow, error) {
	row := q.queryRow(ctx, q.getRawCertStmt, getRawCert, id)
	var i GetRawCertRow
	err := row.Scan(&i.Cert, &i.Key)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT upn, fullname, password, mfa_token, azuread_oid FROM users WHERE upn = $1 LIMIT 1
`

// DO NOT RUN THIS FILE. It is used along with sqlc to generate type safe Go from SQL
func (q *Queries) GetUser(ctx context.Context, upn string) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, upn)
	var i User
	err := row.Scan(
		&i.Upn,
		&i.Fullname,
		&i.Password,
		&i.MfaToken,
		&i.AzureadOid,
	)
	return i, err
}

const newAzureADUser = `-- name: NewAzureADUser :exec
INSERT INTO users(upn, fullname, azuread_oid) VALUES($1, $2, $3)
`

type NewAzureADUserParams struct {
	Upn        string         `json:"upn"`
	Fullname   string         `json:"fullname"`
	AzureadOid sql.NullString `json:"azuread_oid"`
}

func (q *Queries) NewAzureADUser(ctx context.Context, arg NewAzureADUserParams) error {
	_, err := q.exec(ctx, q.newAzureADUserStmt, newAzureADUser, arg.Upn, arg.Fullname, arg.AzureadOid)
	return err
}

const newDevice = `-- name: NewDevice :exec

INSERT INTO devices(udid, state, enrollment_type, name, serial_number, operating_system, azure_did, enrolled_by) VALUES($1, $2, $3, $4, $5, $6, $7, $8)
`

type NewDeviceParams struct {
	Udid            string         `json:"udid"`
	State           DeviceState    `json:"state"`
	EnrollmentType  EnrollmentType `json:"enrollment_type"`
	Name            string         `json:"name"`
	SerialNumber    string         `json:"serial_number"`
	OperatingSystem string         `json:"operating_system"`
	AzureDid        string         `json:"azure_did"`
	EnrolledBy      string         `json:"enrolled_by"`
}

// TODO: Insert or Update
func (q *Queries) NewDevice(ctx context.Context, arg NewDeviceParams) error {
	_, err := q.exec(ctx, q.newDeviceStmt, newDevice,
		arg.Udid,
		arg.State,
		arg.EnrollmentType,
		arg.Name,
		arg.SerialNumber,
		arg.OperatingSystem,
		arg.AzureDid,
		arg.EnrolledBy,
	)
	return err
}

const newDeviceCacheNode = `-- name: NewDeviceCacheNode :exec
INSERT INTO device_cache(device_id, payload_id) VALUES ($1, $2)
`

type NewDeviceCacheNodeParams struct {
	DeviceID  int32 `json:"device_id"`
	PayloadID int32 `json:"payload_id"`
}

func (q *Queries) NewDeviceCacheNode(ctx context.Context, arg NewDeviceCacheNodeParams) error {
	_, err := q.exec(ctx, q.newDeviceCacheNodeStmt, newDeviceCacheNode, arg.DeviceID, arg.PayloadID)
	return err
}

const newDeviceReplacingExisting = `-- name: NewDeviceReplacingExisting :exec
UPDATE devices SET state=$2, enrollment_type=$3, name=$4, serial_number=$5, operating_system=$6, azure_did=$7, nodecache_version='', lastseen=NOW(), lastseen_status=0, enrolled_at=NOW(), enrolled_by=$8 WHERE udid = $1
`

type NewDeviceReplacingExistingParams struct {
	Udid            string         `json:"udid"`
	State           DeviceState    `json:"state"`
	EnrollmentType  EnrollmentType `json:"enrollment_type"`
	Name            string         `json:"name"`
	SerialNumber    string         `json:"serial_number"`
	OperatingSystem string         `json:"operating_system"`
	AzureDid        string         `json:"azure_did"`
	EnrolledBy      string         `json:"enrolled_by"`
}

func (q *Queries) NewDeviceReplacingExisting(ctx context.Context, arg NewDeviceReplacingExistingParams) error {
	_, err := q.exec(ctx, q.newDeviceReplacingExistingStmt, newDeviceReplacingExisting,
		arg.Udid,
		arg.State,
		arg.EnrollmentType,
		arg.Name,
		arg.SerialNumber,
		arg.OperatingSystem,
		arg.AzureDid,
		arg.EnrolledBy,
	)
	return err
}

const newDeviceReplacingExistingReset = `-- name: NewDeviceReplacingExistingReset :exec
DELETE FROM device_cache WHERE device_id=$1
`

func (q *Queries) NewDeviceReplacingExistingReset(ctx context.Context, deviceID int32) error {
	_, err := q.exec(ctx, q.newDeviceReplacingExistingResetStmt, newDeviceReplacingExistingReset, deviceID)
	return err
}

const settings = `-- name: Settings :one
SELECT tenant_name, tenant_email, tenant_website, tenant_phone, tenant_azureid, disable_enrollment FROM settings LIMIT 1
`

func (q *Queries) Settings(ctx context.Context) (Setting, error) {
	row := q.queryRow(ctx, q.settingsStmt, settings)
	var i Setting
	err := row.Scan(
		&i.TenantName,
		&i.TenantEmail,
		&i.TenantWebsite,
		&i.TenantPhone,
		&i.TenantAzureid,
		&i.DisableEnrollment,
	)
	return i, err
}
